# Generated by Django 2.2 on 2020-09-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=120, verbose_name='Product')),
                ('weight', models.CharField(max_length=120, verbose_name='Weight')),
                ('cut_details', models.CharField(max_length=120, verbose_name='Cut Details')),
                ('count', models.CharField(max_length=120, verbose_name='Count Per Kg')),
                ('rate', models.CharField(max_length=120, verbose_name='Rate')),
                ('availability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=120, verbose_name='Availibility')),
            ],
        ),
    ]
