# Generated by Django 2.2 on 2020-09-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_maker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Item',
        ),
    ]
