# Generated by Django 2.2 on 2020-09-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_maker', '0002_auto_20200926_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
    ]
