# Generated by Django 2.2 on 2020-10-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_maker', '0003_remove_item_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cut_details',
        ),
        migrations.AddField(
            model_name='item',
            name='net_wt',
            field=models.CharField(default='', max_length=120, verbose_name='Net Weight'),
        ),
    ]
