# Generated by Django 2.2 on 2020-10-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_maker', '0005_auto_20201014_0522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
