# Generated by Django 2.2 on 2020-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_maker', '0006_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=120, verbose_name='Product')),
                ('net_wt', models.CharField(max_length=120, verbose_name='Net Weight')),
                ('rate', models.CharField(max_length=120, verbose_name='Rate')),
                ('availability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=120, verbose_name='Availibility')),
            ],
        ),
    ]
